### ISSUE TITLE
Setup the Unreal Engine project

### ISSUE THREAD

**Issue by SijmenHuizenga** [FS-Online/Driverless-Competition-Simulator#1]
Add the UE4 project to this repository. We have to research best practices regarding UE4 projects in git/github. 

- [x] Create a new project, give it a nice name and add it to git
- [x] Populate it with an (empty) airsim project
- [x] Check the license for all added content 
- [x] Add any required attributions in the readme
- [x] Document how to get this project running on a new machine, including airsim documentation references.

**Comment by davidoort** [comment]
Seems like all the checkboxes are done. I will test that I can launch the Unreal Editor with the technion car from here

**Comment by davidoort** [comment]
okay, I'll give you some time before testing this

**Comment by SijmenHuizenga** [comment]
I believe you tested it right @davidoort?

**Comment by davidoort** [comment]
YES! I am now testing the project from this repo with the Unreal Installation on the old GCP instances. This task is done
