### ISSUE TITLE
F07 Are cone physics realistic?

### ISSUE THREAD

**Issue by SijmenHuizenga** [FS-Online/Driverless-Competition-Simulator#10]
Cones must move according to real physics! When a cone is hit, it must move or fall over. This task is to investigate the default cone behavior. Is it good enough? If not, make a follow-up task describing what needs to be improved.

**Comment by Riliano** [comment]
Realistic? No. Good enough? Probably yes. I've played a bit with cones and while they can sometimes get stuck in the ground when hit, they do definitly move when hit (and only hit). In my opinion we can use them as is and only iron a few kinks if we have time later on.

**Comment by SijmenHuizenga** [comment]
Thanks for testing this @Riliano! If we find specific problems we can create new tasks for it.
