### ISSUE TITLE
Add a section to the GCP setup doc for developers who have access to the FSOnline GCP project 

### ISSUE THREAD

**Issue by davidoort** [FS-Online/Driverless-Competition-Simulator#15]
This would consist of a lot less steps and just show how to create a VM instance and what snapshot to use. At this point this is only aimed at developers in the sim-dev team (from FSTD), but at some point it might be relevant for other teams who want to get a remote simulation environment setup quickly for testing

**Comment by SijmenHuizenga** [comment]
Since this issue was created, docs on how to prepare new google cloud instances from the ground up to develop have been written and are currently available on master.

A separate ticket has been created here to provide a shared snapshot #77
