### ISSUE TITLE
F21 Car Dynamic Model

### ISSUE THREAD

**Issue by SijmenHuizenga** [FS-Online/Driverless-Competition-Simulator#2]
Airsim uses [this code](https://github.com/microsoft/AirSim/tree/master/Unreal/Plugins/AirSim/Source/Vehicles/Car) to move the car according to inputs. It is pretty good but we require an individual four-wheel motor model. The input must be 4x motor torques and 1x steering angle. We have to create our own by copying this model and changing it.

This also involves changing the [CarControls message](https://github.com/microsoft/AirSim/blob/1cef6f2c60735a74a6e8d5f443e5384aba135b12/PythonClient/airsim/types.py#L285) so that the four-wheel car can actually be controlled remotely.

**Comment by SijmenHuizenga** [comment]
We concluded that creating a 4-wheel torque dynamic model is quite a lot of work compared to the gains. We also suspect that some teams run their algorithms that calculate individual wheel torques based on targeted speed and direction separate from their autonomous systems, maybe even on embedded system. It therefore could be a lot of work for teams to move this code to be part of their simulated autonomous systems.

Because of all this uncertainty we have decided to hold this task for now.

**Comment by davidoort** [comment]
One of the things I would add to this investigation is to switch the current vehicle model from combustion (geared) to electric.

**Comment by davidoort** [comment]
The Unreal Engine repository contains (as a third party library) the code for [PhysX](https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/guide/Manual/Vehicles.html) vehicles that was developed by Nvidia. Airsim simply interacts with the PhysXCar API in [these](https://github.com/FS-Online/Driverless-Competition-Simulator/tree/93fa784106c70e53e973e6d755ab5430feeef9da/UE4Project/Plugins/AirSim/Source/Vehicles/Car) files, which have configurable parameters exposed in the uassets files [here](https://github.com/FS-Online/Driverless-Competition-Simulator/tree/master/UE4Project/Plugins/AirSim/Content/VehicleAdv/SUV)
