### ISSUE TITLE
Monitoring ROS-Bridge

### ISSUE THREAD

**Issue by SijmenHuizenga** [FS-Online/Driverless-Competition-Simulator#41]
We have to know how the ros-bridge is performing. Because if the simulation breaks, we have to be able to prove that the autonomous system was receiving sensordata correctly. This will determinate if a team gets a retry. We are going to do this by measuring all the things:

- [x] RPC Call delay: Track the time that it takes for rpc calls to complete. We can measure this by adding a timing block in the ros-bridge. Note the timestamp before requesting and calculating the difference to the current timestamp when it completes.
- [x] Actual publishing frequency: Track the frequency at which we are publishing to the sensor topics.
- [x] Control-commands frequency: Track the frequency at which we are receiving control commands.

All these statistics should be printed to the console once a second.

**Comment by davidoort** [comment]
See https://github.com/FS-Online/Driverless-Competition-Simulator/pull/58
