### ISSUE TITLE
Import ZalaZone map into project

### ISSUE THREAD

**Issue by SijmenHuizenga** [FS-Online/Driverless-Competition-Simulator#45]
We want to use the [zalazone maps](https://github.com/BMEAutomatedDrive/ZalaZONE-automotive-proving-ground-virtual-simulation-models). Let's get those imported in this project, setup an example track and make the car drive in here.

**Comment by SijmenHuizenga** [comment]
Some time ago I gave this a try but couldn't get it to work. I raised a question [here](https://github.com/BMEAutomatedDrive/ZalaZONE-automotive-proving-ground-virtual-simulation-models/issues/1)

**Comment by davidoort** [comment]
What is wrong with the current maps?

**Comment by SijmenHuizenga** [comment]
We would rather use the ZalaZone maps because they are one of the big sponsors of the FS-East event.

**Comment by SijmenHuizenga** [comment]
Importing the fbx file with scaling 100 makes it really big but still I only see the individual objects. Since there is no response to the github issue, I sent a dm to their facebook group.

**Comment by SijmenHuizenga** [comment]
Import worked! See the linked linked ticket for tutorial. Seeing this map we have to discuss how we want to use it.
