### ISSUE TITLE
Run FSTD autonomous system on simulator

### ISSUE THREAD

**Issue by davidoort** [FS-Online/Driverless-Competition-Simulator#53]
This is an epic task that will require some work on the AS side (mostly CV, controls and SE) which will bring out a lot of bugs in the simulator and serve as proof for other teams that this pipeline can work!

For this the first step is to give a heads up to the following people:

- Charlie (Controls)
- Ben (Controls)
- Sibo (ML)
- Nick (Lidar and CV)
- Ravi (Infra and CV)
- Paul (Lidar)

and organize a Hackathon!

**Comment by SijmenHuizenga** [comment]
@davidoort let's move this oke?

**Comment by SijmenHuizenga** [comment]
Closing because moved to internal repo
