### ISSUE TITLE
Simulator v1

### ISSUE THREAD

**Issue by SijmenHuizenga** [FS-Online/Driverless-Competition-Simulator#9]
The simulator program will be the 'head quarters' of this system. The competition officials will be able control the events using a gui provided by the simulator, the autonomous systems will connect to the simulator to retrieve sensor data and send trajectory setpoints. 

The challenge in this task is to create the first version of this program. 

It must be able to connects to airsim and retreives lidar + camera stream from the car. It must wait for a start signal (an http post requset to some endpoint will suffice). When the start signal is received the camera and lidar stream must be forwarded to an external autonomous system through ros. Publishing on a ros topic is good enough for now. The simulator must listen on a ros topic for car setpoints and forward those to the car inside airsim.

This program must be built in python.

**Comment by davidoort** [comment]
You mentioned that a way to achieve this would be to build on/modify the ros wrapper for airsim, however that is written fully in C++, so I guess using C++ is not out of the question?

**Comment by SijmenHuizenga** [comment]
> You mentioned that a way to achieve this would be to build on/modify the ros wrapper for airsim, however that is written fully in C++, so I guess using C++ is not out of the question?

Sorry! I must have misremembered this. If you guys want to do C++ i am fine with that but if you want to rewrite the useful parts to python that's also fine with me.

**Comment by SijmenHuizenga** [comment]
This shouln't be closed

**Comment by davidoort** [comment]
Waiting for @mvanlobensels to close this. The ROS part is done

**Comment by SijmenHuizenga** [comment]
First version was merged in #20, follow up tasks are #28 and #29
